version: '2'
services:
  swellrt:
    image: p2pvalue/swellrt:${SWELLRT_VERSION}
    hostname: swellrt
    restart: always
    depends_on:
      - mongo
    ports:
      - "0.0.0.0:9898:9898"
    volumes:
      - ./config:/usr/local/swellrt/config
    environment:
      MONGODB_HOST: "mongo"
  mongo:
    image: mongo:latest
    restart: always



